<a href="https://colab.research.google.com/github/bandarismr135-spec/firstproject/blob/main/pandas_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# create 50 users * 7 days array
# what is the shape and datatype of the array
# Find the total steps each day by summming column wise
#

In [ ]:
import numpy as np

steps = np.random.randint(1000, 15000, size=(50, 7))


In [ ]:
print("Shape:",steps.shape)

Shape: (50, 7)


In [ ]:
print("Datatype:",steps.dtype)

Datatype: int64


In [ ]:
import numpy as np
data = np.random.randint(1, 101, size=(50, 7))
print(data)


[[  7  27  66   9  89   1  57]
 [ 62  47  91  23  97  12   9]
 [ 78  13  29  36  43  96  94]
 [  6  61  66  97  61  16  62]
 [ 44   3  53  25  55  30  36]
 [ 11  98  43  73  27   2  36]
 [ 26  40  86  82   7  89  33]
 [  1  41  70  41  27   1  50]
 [ 71  75  58  33  69  47  23]
 [ 20  23  76  69  61   6  40]
 [ 45  50  30   1  17  18  65]
 [ 73  54  18  63  71  86  23]
 [ 75  83  71  12  76   8  20]
 [ 63  67   6  45  52  42  18]
 [ 26  59  25  13  23  58  77]
 [ 15  50  43  31  35 100  65]
 [ 47  38  17  96  79  95  96]
 [  8  44  42  25  19  95 100]
 [ 82  60  53  79  18  79  68]
 [ 59   5  63  95  47  58  35]
 [ 59  33  51  28  81  89  84]
 [ 53  76  87  22  48  55  63]
 [ 75  58  68  69  72  55  89]
 [ 87  46  16  29   6  48  78]
 [ 83  90   2  25  63  79  47]
 [ 97  50  74  10  95  71  80]
 [100  56  41  46   1  65  68]
 [ 81  99  32  26  50  27  62]
 [ 24  65  86  32  47  19  31]
 [ 78  92  51  21  23  34  53]
 [ 49  32  56  33  32  71  32]
 [ 40  84  82  32  61  58   6]
 [ 75  4

In [ ]:
subset=steps[:5,:3]
subset

NameError: name 'steps' is not defined

In [ ]:
print("Shape:",steps.shape)

NameError: name 'steps' is not defined

In [ ]:
# PANDAS
from google.colab import files
uploaded=files.upload()

Saving mtcars (1).csv to mtcars (1) (1).csv


In [ ]:
import pandas as pd
df1= pd.read_csv("mtcars (1) (1).csv")

In [ ]:
df1.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [ ]:
#
df1.shape

(32, 12)

In [ ]:
df1.columns

Index(['model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

In [ ]:

# data type of each column
df1.dtypes

model     object
mpg      float64
cyl        int64
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs         int64
am         int64
gear       int64
carb       int64
dtype: object

In [ ]:
# Check all null values
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   model   32 non-null     object 
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64  
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64  
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64  
 9   am      32 non-null     int64  
 10  gear    32 non-null     int64  
 11  carb    32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [ ]:
df1.isnull()

model    mpg    cyl   disp     hp   drat     wt   qsec     vs     am  \
0   False  False  False  False  False  False  False  False  False  False   
1   False  False  False  False  False  False  False  False  False  False   
2   False  False  False  False  False  False  False  False  False  False   
3   False  False  False  False  False  False  False  False  False  False   
4   False  False  False  False  False  False  False  False  False  False   
5   False  False  False  False  False  False  False  False  False  False   
6   False  False  False  False  False  False  False  False  False  False   
7   False  False  False  False  False  False  False  False  False  False   
8   False  False  False  False  False  False  False  False  False  False   
9   False  False  False  False  False  False  False  False  False  False   
10  False  False  False  False  False  False  False  False  False  False   
11  False  False  False  False  False  False  False  False  False  False   
12  False  False  False  False  False  False  False  False  False  False   
13  False  False  False  False  False  False  False  False  False  False   
14  False  False  False  False  False  False  False  False  False  False   
15  False  False  False  False  False  False  False  False  False  False   
16  False  False  False  False  False  False  False  False  False  False   
17  False  False  False  False  False  False  False  False  False  False   
18  False  False  False  False  False  False  False  False  False  False   
19  False  False  False  False  False  False  False  False  False  False   
20  False  False  False  False  False  False  False  False  False  False   
21  False  False  False  False  False  False  False  False  False  False   
22  False  False  False  False  False  False  False  False  False  False   
23  False  False  False  False  False  False  False  False  False  False   
24  False  False  False  False  False  False  False  False  False  False   
25  False  False  False  False  False  False  False  False  False  False   
26  False  False  False  False  False  False  False  False  False  False   
27  False  False  False  False  False  False  False  False  False  False   
28  False  False  False  False  False  False  False  False  False  False   
29  False  False  False  False  False  False  False  False  False  False   
30  False  False  False  False  False  False  False  False  False  False   
31  False  False  False  False  False  False  False  False  False  False   

     gear   carb  
0   False  False  
1   False  False  
2   False  False  
3   False  False  
4   False  False  
5   False  False  
6   False  False  
7   False  False  
8   False  False  
9   False  False  
10  False  False  
11  False  False  
12  False  False  
13  False  False  
14  False  False  
15  False  False  
16  False  False  
17  False  False  
18  False  False  
19  False  False  
20  False  False  
21  False  False  
22  False  False  
23  False  False  
24  False  False  
25  False  False  
26  False  False  
27  False  False  
28  False  False  
29  False  False  
30  False  False  
31  False  False

In [ ]:
df1.isnull().sum()

model    0
mpg      0
cyl      0
disp     0
hp       0
drat     0
wt       0
qsec     0
vs       0
am       0
gear     0
carb     0
dtype: int64

In [ ]:
# statistical summary
df1.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [ ]:
# transpose -- convering rows to cloumns
df1.T

0              1           2               3   \
model  Mazda RX4  Mazda RX4 Wag  Datsun 710  Hornet 4 Drive   
mpg         21.0           21.0        22.8            21.4   
cyl            6              6           4               6   
disp       160.0          160.0       108.0           258.0   
hp           110            110          93             110   
drat         3.9            3.9        3.85            3.08   
wt          2.62          2.875        2.32           3.215   
qsec       16.46          17.02       18.61           19.44   
vs             0              0           1               1   
am             1              1           1               0   
gear           4              4           4               3   
carb           4              4           1               1   

                      4        5           6          7         8         9   \
model  Hornet Sportabout  Valiant  Duster 360  Merc 240D  Merc 230  Merc 280   
mpg                 18.7     18.1        14.3       24.4      22.8      19.2   
cyl                    8        6           8          4         4         6   
disp               360.0    225.0       360.0      146.7     140.8     167.6   
hp                   175      105         245         62        95       123   
drat                3.15     2.76        3.21       3.69      3.92      3.92   
wt                  3.44     3.46        3.57       3.19      3.15      3.44   
qsec               17.02    20.22       15.84       20.0      22.9      18.3   
vs                     0        1           0          1         1         1   
am                     0        0           0          0         0         0   
gear                   3        3           3          4         4         4   
carb                   2        1           4          2         2         4   

       ...           22          23                24         25  \
model  ...  AMC Javelin  Camaro Z28  Pontiac Firebird  Fiat X1-9   
mpg    ...         15.2        13.3              19.2       27.3   
cyl    ...            8           8                 8          4   
disp   ...        304.0       350.0             400.0       79.0   
hp     ...          150         245               175         66   
drat   ...         3.15        3.73              3.08       4.08   
wt     ...        3.435        3.84             3.845      1.935   
qsec   ...         17.3       15.41             17.05       18.9   
vs     ...            0           0                 0          1   
am     ...            0           0                 0          1   
gear   ...            3           3                 3          4   
carb   ...            2           4                 2          1   

                  26            27              28            29  \
model  Porsche 914-2  Lotus Europa  Ford Pantera L  Ferrari Dino   
mpg             26.0          30.4            15.8          19.7   
cyl                4             4               8             6   
disp           120.3          95.1           351.0         145.0   
hp                91           113             264           175   
drat            4.43          3.77            4.22          3.62   
wt              2.14         1.513            3.17          2.77   
qsec            16.7          16.9            14.5          15.5   
vs                 0             1               0             0   
am                 1             1               1             1   
gear               5             5               5             5   
carb               2             2               4             6   

                  30          31  
model  Maserati Bora  Volvo 142E  
mpg             15.0        21.4  
cyl                8           4  
disp           301.0       121.0  
hp               335         109  
drat            3.54        4.11  
wt              3.57        2.78  
qsec            14.6        18.6  
vs                 0           1  
am                 1           1 

In [ ]:
df1['mpg'].min()

10.4

In [ ]:
df1['mpg'].mean()

np.float64(20.090625000000003)

In [ ]:
df1['mpg'].sum()

np.float64(642.9000000000001)

In [ ]:
df1['mpg'].count()

np.int64(32)

In [ ]:
df1['mpg'].avg()

AttributeError: 'Series' object has no attribute 'avg'

In [ ]:
df1.cyl.unique()

array([6, 4, 8])

In [ ]:
# for each clolumn will get that how many unique values
df1.nunique

<bound method DataFrame.nunique of                   model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2  >

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving netflix_titles.csv to netflix_titles.csv


In [ ]:
import pandas as pd
df2=pd.read_csv("netflix.csv")